Lab2_LeVoKhanhMinh/Controllers/DeviceCategoryController.cs
using Lab2_LeVoKhanhMinh.Data;
using Lab2_LeVoKhanhMinh.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lab2_LeVoKhanhMinh.Controllers;

public class DeviceCategoryController : Controller
{
    private readonly ApplicationDbContext _context;

    public DeviceCategoryController(ApplicationDbContext context)
    {
        _context = context;
    }
    // GET
    public IActionResult Index()
    {
        var deviceCategories = _context.DeviceCategories.Include(x => x.Devices).ToList();
        return View(deviceCategories); 
    }
        
    [HttpGet]
    public IActionResult Create()
    {
        ViewBag.Title = "Create New Category";
        return View();
    }

    [HttpPost]
    public IActionResult Create(string CategoryTitle, IFormFile ImageFile)
    {
        if (ModelState.IsValid)
        {
            var maxId = _context.DeviceCategories.Max(x =>(int?) x.Id) ?? 0;
            var nextId = maxId + 1;
            var category = new DeviceCategory
            {
                Id = nextId,
               CategoryTitle = CategoryTitle,
                imageUrl = "images/default-image.png",
            };
            if (ImageFile != null && ImageFile.Length > 0)
            {
                var fileName = Path.GetFileName(ImageFile.FileName);
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    ImageFile.CopyTo(stream);
                }

                category.imageUrl = "images/" + fileName;
            }
            _context.DeviceCategories.Add(category);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        return View();
    }

    [HttpPost]
    public IActionResult Delete(int id)
    {
        var deviceCategory  = _context.DeviceCategories.Find(id);
        if (deviceCategory == null)
        {
            return NotFound();
        }

        if (!string.IsNullOrEmpty(deviceCategory.imageUrl))
        {
            var filePath = Path.Combine("wwwroot", deviceCategory.imageUrl.TrimStart('/'));
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }
        }
        _context.DeviceCategories.Remove(deviceCategory);
        _context.SaveChanges();
        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public IActionResult Edit(int Id)
    
    { 
        
        var deviceCategory = _context.DeviceCategories.Find(Id);
        if (deviceCategory == null)
        {
            Console.WriteLine("Device category not found");
            return NotFound();
        }
        return View(deviceCategory);
    }

    [HttpPost]
    public IActionResult Edit(int Id, string CategoryTitle, IFormFile ImageFile)
    {
       var category  = _context.DeviceCategories.Find(Id);
       if (category == null)
       {
           return NotFound();
       }
       else
       {
           if (ImageFile != null && ImageFile.Length > 0)
           {
               var fileName = Path.GetFileName(ImageFile.FileName);
               var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
               using (var stream = new FileStream(filePath, FileMode.Create))
               {
                   ImageFile.CopyTo(stream);
               }

               category.imageUrl = "images/" + fileName;
           }

           category.CategoryTitle = CategoryTitle;
           _context.Update(category);
           _context.SaveChanges();
       }
        return RedirectToAction(nameof(Index));
    }


    [HttpGet]
    public IActionResult DevicesByCategory(int? deviceCategoryId)
    {
        if (deviceCategoryId == null)
        {
            ViewBag.categories = _context.DeviceCategories.ToList();
        }
        else
        {
            var category = _context.DeviceCategories.Include(d => d.Devices)
                .FirstOrDefault(d => d.Id == deviceCategoryId);
            ViewBag.categories = _context.DeviceCategories.ToList();
            ViewBag.category = category;
        }

        return View();
    }

   
   
}

Lab2_LeVoKhanhMinh/Controllers/DeviceController.cs
using Lab2_LeVoKhanhMinh.Data;
using Lab2_LeVoKhanhMinh.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lab2_LeVoKhanhMinh.Controllers;

public class DeviceController : Controller
{   
    private readonly ApplicationDbContext _context;

    public DeviceController(ApplicationDbContext context)
    {
     _context = context;    
    }
    // GET
    public IActionResult Index()
    {
        var devices = _context.Devices.Include(d => d.DeviceCategory).ToList();
        ViewBag.categories = _context.DeviceCategories.ToList();
        ViewBag.Statuses = Enum.GetValues(typeof(Status)).Cast<Status>().ToList();
        ViewBag.devices = devices;
        return View();
    }

    [HttpGet]
    public IActionResult Create()
    {  
        ViewBag.categories = _context.DeviceCategories.ToList();
        ViewBag.Statuses = Enum.GetValues(typeof(Status)).Cast<Status>().ToList();
        return View();
    }

    [HttpPost]
    public IActionResult Create(Device device)
    {
        if (device == null)
        {
            Console.WriteLine("Device is null");
            return BadRequest();
        }
        var category = _context.DeviceCategories.Find(device.DeviceCategoryId);
        if (category == null)
        {
            return NotFound();
        }
        device.DeviceCategory = category;
        _context.Devices.Add(device);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Delete(int Id)
    {
        var device = _context.Devices.Find(Id);
        _context.Devices.Remove(device);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int deviceId)
    {   
        var device = _context.Devices.Find(deviceId);
        ViewBag.categories = _context.DeviceCategories.ToList();
        ViewBag.Statuses = Enum.GetValues(typeof(Status)).Cast<Status>().ToList();
        ViewBag.device = device;
        return View();
    }

    [HttpPost]
    public IActionResult Edit(Device device)
    {
        var previousDevice = _context.Devices.Find(device.Id);
        if (previousDevice == null)
        {
            return NotFound();
        }
        else
        {
            previousDevice.DeviceCode = device.DeviceCode;
            previousDevice.DeviceName = device.DeviceName;
            previousDevice.Status = device.Status;
            previousDevice.DateOfEntry = device.DateOfEntry;
            previousDevice.DeviceCategoryId = device.DeviceCategoryId;
            previousDevice.DeviceCategory = device.DeviceCategory;
            _context.Devices.Update(previousDevice);
            _context.SaveChanges();
        }
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult AllStatuses()
    {
        ViewBag.filterType = "Status";
        ViewBag.Statuses = Enum.GetValues(typeof(Status)).Cast<Status>().ToList();
        var devices = _context.Devices.Include(d => d.DeviceCategory).ToList();
        ViewBag.devices = devices;
        return View("Index");
    }
    [HttpGet]
    public IActionResult AllCategories()
    {
        ViewBag.filterType = "Category";
        ViewBag.categories = _context.DeviceCategories.ToList();
        var devices = _context.Devices.Include(d => d.DeviceCategory).ToList();
        ViewBag.devices = devices;
        return View("Index");
    }

    [HttpGet]
    public IActionResult Search(string searchTerm)
    {
        var devices = _context.Devices.Include(d => d.DeviceCategory).AsQueryable();
        
        if (!string.IsNullOrEmpty(searchTerm))
        {
            devices = devices.Where(d => d.DeviceName.Contains(searchTerm) || d.DeviceCode.Contains(searchTerm));
        }

        ViewBag.categories = _context.DeviceCategories.ToList();
        ViewBag.Statuses = Enum.GetValues(typeof(Status)).Cast<Status>().ToList();
        ViewBag.devices = devices.ToList();

        return View("Index");  
    }
    [HttpGet]
    public IActionResult FilterDevices(string filterBy, string filterValue)
    {
        var devices = _context.Devices.Include(d => d.DeviceCategory).AsQueryable();

        if (!string.IsNullOrEmpty(filterBy) && !string.IsNullOrEmpty(filterValue))
        {
            if (filterBy == "Category")
            {
                var categoryId = Convert.ToInt32(filterValue);
                devices = devices.Where(d => d.DeviceCategoryId == categoryId);
            }
            else if (filterBy == "Status")
            {
                devices = devices.Where(d => d.Status.ToString() == filterValue);
            }
        }

        ViewBag.devices= devices.ToList();
        ViewBag.categories = _context.DeviceCategories.ToList();
        ViewBag.Statuses = Enum.GetValues(typeof(Status)).Cast<Status>().ToList();
        return PartialView("Index"); 
    }

  
}

Lab2_LeVoKhanhMinh/Controllers/UserController.cs
using Lab2_LeVoKhanhMinh.Data;
using Lab2_LeVoKhanhMinh.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab2_LeVoKhanhMinh.Controllers;

public class UserController : Controller
{
    // GET
    private readonly ApplicationDbContext _context;

    public UserController(ApplicationDbContext context)
    {
        _context = context;
    }
    
    public IActionResult Index()
    {
        var users = _context.Users.ToList();
        return View(users);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Create(User user)
    {
        if (ModelState.IsValid)
        {
            _context.Users.Add(user);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        return View("Index");
    }

   [HttpGet]
    public IActionResult Edit(int id)
    {
        var user = _context.Users.Find(id);
        if (user == null)
        {
            return NotFound();
        }
        return View(user);
    }
    
    [HttpPost]
    public IActionResult Edit( User user)
    {
        if (user.Id != user.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            _context.Users.Update(user);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        return View(user);
    }
    
    [HttpPost]
    public IActionResult Delete(int id)
    {
        var user = _context.Users.Find(id);
        if (user == null)
        {
            return NotFound();
        }

        _context.Users.Remove(user);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }
}

Lab2_LeVoKhanhMinh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Lab2_LeVoKhanhMinh</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Lab2_LeVoKhanhMinh.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <script !src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab2_LeVoKhanhMinh</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="DeviceCategory" asp-action="Index">Device Category</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users Management</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - Lab2_LeVoKhanhMinh - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Lab2_LeVoKhanhMinh/Views/Shared/_LayoutForAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
<div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar">
        <div class="custom-menu">
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
                <i class="fa fa-bars"></i>
                <span class="sr-only">Toggle Menu</span>
            </button>
        </div>
        <h1><a href="#" class="logo">Device Management</a></h1>
        <ul class="list-unstyled components mb-5">
            <li class="active">
                <a asp-controller="Home" asp-action="Index"><span class="fa fa-home mr-3"></span> Homepage</a>
            </li>
            <li>
                <a asp-controller="DeviceCategory" asp-action="Index"><span class="fa fa-user mr-3"></span>Device Category</a>
            </li>
            <li>
                <a asp-controller="DeviceCategory" asp-action="Create"><span class="fa fa-sticky-note mr-3"></span>Add Category</a>
            </li>
            <li>
                <a asp-controller="Device" asp-action="Index"><span class="fa fa-sticky-note mr-3"></span>Devices</a>
            </li>
            <li>
                <a  asp-controller="Device" asp-action="Create"><span class="fa fa-paper-plane mr-3"></span>Add Device</a>
            </li>
            <li>
                <a asp-controller="DeviceCategory" asp-action="DevicesByCategory"><span class="fa fa-sticky-note mr-3"></span>Devices By Category</a>
            </li>
           
           
        </ul>

    </nav>
    
    <div id="content" class="p-4 p-md-5 pt-5">
        @RenderBody()
    </div>
</div>
<script src="~/js/site.js"></script>
<script src="~/js/jquery.min.js"></script>
<script src="~/js/popper.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/main.js"></script>




</body>
</html>